// src/bridge/mod.rs – C‑Bridge main module

mod generator;
mod parser;

use crate::diagnostic::{Diagnostic, debug_log, emit_diagnostic};
use std::fs;
use std::path::{Path, PathBuf};

/// Represents a foreign function (used externally by other compiler modules).
#[derive(Debug, Clone, PartialEq)]
pub struct ForeignFunction {
    pub name: String,
    pub param_types: Vec<String>,
    pub return_type: String,
}

/// Bridge a C header file to Vox code.
/// Returns the generated Vox source as a string.
///
/// # Limitations
/// - Does not recursively process `#include` directives.
/// - Does not respect `-I` include paths.
/// - Only parses simple function declarations (no structs, enums, or function pointers).
pub fn bridge_header(header_path: &Path) -> Result<String, String> {
    debug_log(format!(
        "bridge: reading header '{}'",
        header_path.display()
    ));

    let src = fs::read_to_string(header_path)
        .map_err(|e| format!("Failed to read header '{}': {}", header_path.display(), e))?;

    let functions = parser::parse_header(&src)
        .map_err(|e| format!("Parse error in '{}': {}", header_path.display(), e))?;

    if functions.is_empty() {
        let diag = Diagnostic::warning(format!(
            "No functions found in header: {}",
            header_path.display()
        ))
        .with_code("VX0302");
        emit_diagnostic(&diag);
    }

    let mut output = String::new();
    output.push_str("// Auto‑generated by Vox C‑Bridge\n");
    output.push_str(&format!("// Source: {}\n", header_path.display()));
    output.push_str("// Do not edit manually\n\n");

    for func in functions {
        match generator::generate_vox_decl(&func) {
            Ok(decl) => {
                output.push_str(&decl);
                output.push('\n');
            }
            Err(diag) => {
                // Diagnostic already emitted inside generate_vox_decl
                debug_log(format!(
                    "bridge: skipping function '{}' due to error",
                    func.name
                ));
                continue;
            }
        }
    }

    Ok(output)
}

/// Helper to bridge a header by name (looks in current directory only).
pub fn bridge_header_by_name(name: &str) -> Result<String, String> {
    let path = PathBuf::from(name);
    bridge_header(&path)
}
