// src/codegen/msl.rs – Metal Shading Language (MSL) generator for Voxlang.
//
// UPDATED (Phase 1): Scalar parameters are now packed into a single struct
// and passed as a buffer, as required by MSL. This fixes the compiler error
// where `int a` is rejected in kernel signatures.
//
// PHASE 4 (2026-06-29): Implemented `match` expression support for MSL.
// Supports `Option`, `Result`, and custom enums with `UnitVariant` and
// `Binding` patterns.

use crate::codegen::CodegenEngine;
use crate::diagnostic::{Diagnostic, emit_diagnostic};
use crate::parser::{ASTNode, MatchArm, MatchPattern, Param};
use std::collections::HashMap;

/// Generate Metal Shading Language (MSL) source from a Vox AST.
pub fn generate_msl(engine: &mut CodegenEngine, ast: &ASTNode) -> String {
    let mut emitter = MslEmitter::new(engine);
    emitter.generate(ast)
}

// ----------------------------------------------------------------------------
// MSL Emitter – holds state and emits MSL code
// ----------------------------------------------------------------------------
struct MslEmitter<'a> {
    engine: &'a mut CodegenEngine,
    output: String,
    indent: usize,
    kernel_names: Vec<String>,
    type_cache: HashMap<String, String>,
    emitted_structs: Vec<String>,
    current_function: Option<String>,
    // Mapping from scalar parameter name to the access expression (e.g., "args->field")
    scalar_access_map: HashMap<String, String>,
    // For match expression: mapping from binding name to the payload access expression
    match_binding_map: HashMap<String, String>,
}

impl<'a> MslEmitter<'a> {
    fn new(engine: &'a mut CodegenEngine) -> Self {
        Self {
            engine,
            output: String::new(),
            indent: 0,
            kernel_names: Vec::new(),
            type_cache: HashMap::new(),
            emitted_structs: Vec::new(),
            current_function: None,
            scalar_access_map: HashMap::new(),
            match_binding_map: HashMap::new(),
        }
    }

    fn generate(&mut self, ast: &ASTNode) -> String {
        self.output.clear();
        self.emit_header();
        self.emit_struct_definitions(ast);
        self.emit_kernel_functions(ast);
        std::mem::take(&mut self.output)
    }

    // ------------------------------------------------------------------------
    // Header and utilities
    // ------------------------------------------------------------------------
    fn emit_header(&mut self) {
        self.push_line("// Metal Shading Language generated by Voxlang");
        self.push_line("#include <metal_stdlib>");
        self.push_line("using namespace metal;");
        self.push_line("");
    }

    fn push_line(&mut self, line: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&indent_str);
        self.output.push_str(line);
        self.output.push('\n');
    }

    fn push_block<F>(&mut self, header: &str, f: F)
    where
        F: FnOnce(&mut Self),
    {
        self.push_line(&format!("{} {{", header));
        self.indent += 1;
        f(self);
        self.indent -= 1;
        self.push_line("}");
    }

    // ------------------------------------------------------------------------
    // Type mapping: Vox -> MSL
    // ------------------------------------------------------------------------
    fn map_type(&mut self, vox_ty: &str) -> String {
        if let Some(msl) = self.type_cache.get(vox_ty) {
            return msl.clone();
        }
        let expanded = self.engine.expand_type_aliases(vox_ty);
        let result = self.map_type_inner(&expanded);
        self.type_cache.insert(vox_ty.to_string(), result.clone());
        result
    }

    fn map_type_inner(&mut self, vox_ty: &str) -> String {
        let trimmed = vox_ty.trim();

        let msl = match trimmed {
            "i8" => "char".to_string(),
            "i16" => "short".to_string(),
            "i32" => "int".to_string(),
            "i64" => "long".to_string(),
            "u8" => "uchar".to_string(),
            "u16" => "ushort".to_string(),
            "u32" => "uint".to_string(),
            "u64" => "ulong".to_string(),
            "f32" => "float".to_string(),
            "f64" => "double".to_string(),
            "bool" => "bool".to_string(),
            "char" => "int".to_string(),
            "void" => "void".to_string(),
            "usize" => "uint".to_string(),
            s if s.starts_with("&mut ") => {
                let inner = self.map_type(&s[5..]);
                format!("device {}*", inner)
            }
            s if s.starts_with("& ") => {
                let inner = self.map_type(&s[2..]);
                format!("constant {}*", inner)
            }
            s if s.starts_with("[]") => {
                let inner = self.map_type(&s[2..]);
                format!("device {}*", inner)
            }
            s if s.starts_with('[') && s.contains('x') => {
                let parts: Vec<&str> = s.split('x').collect();
                if parts.len() == 2 {
                    let len = parts[0].trim_start_matches('[').trim();
                    let elem = parts[1].trim_end_matches(']').trim();
                    let elem_msl = self.map_type(elem);
                    if let Ok(n) = len.parse::<usize>() {
                        format!("array<{}, {}>", elem_msl, n)
                    } else {
                        format!("device {}*", elem_msl)
                    }
                } else {
                    "int".to_string()
                }
            }
            "String" | "&str" => "device char*".to_string(),
            s if s.starts_with("Vec<") => {
                let inner = &s[4..s.len() - 1];
                let inner_msl = self.map_type(inner);
                format!("device {}*", inner_msl)
            }
            s if s.starts_with("HashMap<") => "device void*".to_string(),
            s if s.starts_with("Option<") => {
                let inner = &s[7..s.len() - 1];
                let inner_msl = self.map_type(inner);
                let struct_name = format!("Option_{}", self.sanitize_identifier(&inner_msl));
                self.ensure_option_struct(&struct_name, &inner_msl);
                struct_name
            }
            s if s.starts_with("Result<") => {
                let inner = &s[7..s.len() - 1];
                if let Some(comma) = inner.find(',') {
                    let ok_ty = inner[..comma].trim();
                    let err_ty = inner[comma + 1..].trim();
                    let ok_msl = self.map_type(ok_ty);
                    let err_msl = self.map_type(err_ty);
                    let struct_name = format!(
                        "Result_{}_{}",
                        self.sanitize_identifier(&ok_msl),
                        self.sanitize_identifier(&err_msl)
                    );
                    self.ensure_result_struct(&struct_name, &ok_msl, &err_msl);
                    struct_name
                } else {
                    "int".to_string()
                }
            }
            s if self.engine.struct_fields.contains_key(s) => s.to_string(),
            s if self.engine.enum_variants.contains_key(s) => "int".to_string(),
            _ => "int".to_string(),
        };
        msl
    }

    /// Determine if a Vox type is a scalar (basic type) that should be packed into the argument struct.
    fn is_scalar_type(&self, vox_ty: &str) -> bool {
        match vox_ty.trim() {
            "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64"
            | "bool" | "char" | "usize" => true,
            _ => false,
        }
    }

    /// Determine if a Vox type is an enum (Option, Result, or custom enum).
    fn is_enum_type(&self, vox_ty: &str) -> bool {
        let base = CodegenEngine::strip_generic_args(vox_ty);
        let base_no_module = CodegenEngine::strip_module_prefix(&base);
        self.engine.enum_variants.contains_key(&base_no_module)
    }

    /// Get the discriminant value for an enum variant.
    fn get_enum_discriminant(&self, enum_name: &str, variant_name: &str) -> Option<u32> {
        let base = CodegenEngine::strip_generic_args(enum_name);
        let base_no_module = CodegenEngine::strip_module_prefix(&base);
        if let Some(variants) = self.engine.enum_variants.get(&base_no_module) {
            variants.get(variant_name).copied()
        } else {
            None
        }
    }

    fn sanitize_identifier(&self, s: &str) -> String {
        s.chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>()
    }

    fn ensure_option_struct(&mut self, struct_name: &str, inner_msl: &str) {
        let def = format!(
            "struct {} {{ bool has_value; {} value; }};",
            struct_name, inner_msl
        );
        if !self.emitted_structs.contains(&def) {
            self.emitted_structs.push(def.clone());
            self.engine
                .pending_concrete_struct_defs
                .borrow_mut()
                .push(def);
        }
    }

    fn ensure_result_struct(&mut self, struct_name: &str, ok_msl: &str, err_msl: &str) {
        let def = format!(
            "struct {} {{ bool is_ok; {} ok; {} err; }};",
            struct_name, ok_msl, err_msl
        );
        if !self.emitted_structs.contains(&def) {
            self.emitted_structs.push(def.clone());
            self.engine
                .pending_concrete_struct_defs
                .borrow_mut()
                .push(def);
        }
    }

    // ------------------------------------------------------------------------
    // Emit struct definitions (user-defined structs)
    // ------------------------------------------------------------------------
    fn emit_struct_definitions(&mut self, ast: &ASTNode) {
        if let ASTNode::Program(stmts, _) = ast {
            for stmt in stmts {
                if let ASTNode::StructDef { name, fields, .. } = stmt {
                    let mut field_decls = Vec::new();
                    for f in fields {
                        let msl_ty = self.map_type(&f.ty);
                        field_decls.push(format!("{} {};", msl_ty, f.name));
                    }
                    let struct_def = format!("struct {} {{ {} }};", name, field_decls.join(" "));
                    self.push_line(&struct_def);
                }
            }
        }
    }

    // ------------------------------------------------------------------------
    // Kernel function emission
    // ------------------------------------------------------------------------
    fn emit_kernel_functions(&mut self, ast: &ASTNode) {
        if let ASTNode::Program(stmts, _) = ast {
            for stmt in stmts {
                if let ASTNode::KernelFn {
                    name,
                    params,
                    body,
                    device_triple: _,
                    attr,
                    span,
                } = stmt
                {
                    self.kernel_names.push(name.clone());
                    self.emit_kernel(name, params, body, attr, *span);
                }
            }
        }
    }

    fn emit_kernel(
        &mut self,
        name: &str,
        params: &[Param],
        body: &[ASTNode],
        _attr: &crate::parser::KernelAttr,
        _span: crate::frontend::span::Span,
    ) {
        // Clear any previous scalar mapping
        self.scalar_access_map.clear();

        // 1. Categorize parameters: scalars vs. buffers
        let mut scalar_params = Vec::new(); // (name, msl_type)
        let mut buffer_params = Vec::new(); // (name, msl_type, is_reference)

        for param in params {
            let msl_ty = self.map_type(&param.ty);
            let is_ref = param.ty.starts_with('&')
                || param.ty.starts_with("[]")
                || param.ty.starts_with('[')
                || param.ty.starts_with("Vec<")
                || param.ty.starts_with("HashMap<")
                || param.ty.starts_with("Option<")
                || param.ty.starts_with("Result<")
                || self.engine.struct_fields.contains_key(&param.ty)
                || self.engine.enum_variants.contains_key(&param.ty);

            // Scalar if not a reference and not a composite type (struct/enum) and is a basic type.
            // We use is_scalar_type to decide.
            let is_scalar = !is_ref && self.is_scalar_type(&param.ty);

            if is_scalar {
                scalar_params.push((param.name.clone(), msl_ty));
            } else {
                // For buffers, we also need to know if it's a pointer/reference.
                // But the msl_ty already includes device/constant.
                // We'll store the MSL type as is.
                buffer_params.push((param.name.clone(), msl_ty, is_ref));
            }
        }

        // 2. Emit scalar argument struct if needed
        let scalar_struct_name = format!("KernelArgs_{}", name);
        if !scalar_params.is_empty() {
            let mut field_decls = Vec::new();
            for (_, msl_ty) in &scalar_params {
                // Use the same field order as in scalar_params
                // We'll generate field names like f0, f1, ... to keep it simple.
                // But we could use the parameter names; they are valid identifiers.
                // However, using the original names might conflict with other identifiers.
                // We'll use the original names for clarity, but we need to ensure they are valid MSL identifiers.
                // We'll sanitize just in case.
                let field_name = self.sanitize_identifier(&scalar_params[field_decls.len()].0);
                field_decls.push(format!("{} {};", msl_ty, field_name));
            }
            let struct_def = format!(
                "struct {} {{ {} }};",
                scalar_struct_name,
                field_decls.join(" ")
            );
            self.push_line(&struct_def);

            // Build mapping from parameter name to access expression
            for (_i, (param_name, _)) in scalar_params.iter().enumerate() {
                let field_name = self.sanitize_identifier(param_name);
                self.scalar_access_map
                    .insert(param_name.clone(), format!("args->{}", field_name));
            }
        }

        // 3. Build kernel parameter list
        let mut param_decls = Vec::new();
        let mut buffer_index = 0;

        // If there are scalars, add the scalar struct buffer at index 0
        if !scalar_params.is_empty() {
            let attr = format!("[[buffer({})]]", buffer_index);
            param_decls.push(format!("device {}* args {}", scalar_struct_name, attr));
            buffer_index += 1;
        }

        // Add each buffer parameter with increasing indices
        for (param_name, msl_ty, _) in &buffer_params {
            let attr = format!("[[buffer({})]]", buffer_index);
            param_decls.push(format!("{} {} {}", msl_ty, param_name, attr));
            buffer_index += 1;
        }

        // 4. Emit kernel signature and body
        self.push_line(&format!(
            "kernel void {}({}) {{",
            name,
            param_decls.join(", ")
        ));
        self.indent += 1;
        self.current_function = Some(name.to_string());

        // Emit statements; the scalar mapping will be used in emit_expression
        for stmt in body {
            self.emit_statement(stmt);
        }

        self.indent -= 1;
        self.push_line("}");
        self.current_function = None;
        self.push_line("");
    }

    // ------------------------------------------------------------------------
    // Statement emission
    // ------------------------------------------------------------------------
    fn emit_statement(&mut self, node: &ASTNode) {
        match node {
            ASTNode::VariableDecl {
                name,
                ty,
                value,
                mutable,
                ..
            } => {
                let ty_str = ty.as_deref().unwrap_or("i32");
                let msl_ty = self.map_type(ty_str);
                let init = self.emit_expression(value);
                let mut_decl = if *mutable { "var" } else { "let" };
                self.push_line(&format!("{} {}: {} = {};", mut_decl, name, msl_ty, init));
            }
            ASTNode::Assignment { lhs, value, .. } => {
                let lhs_str = self.emit_expression(lhs);
                let rhs = self.emit_expression(value);
                self.push_line(&format!("{} = {};", lhs_str, rhs));
            }
            ASTNode::IfStatement {
                condition,
                then_branch,
                else_branch,
                ..
            } => {
                let cond = self.emit_expression(condition);
                self.push_block(&format!("if ({})", cond), |this| {
                    for stmt in then_branch {
                        this.emit_statement(stmt);
                    }
                });
                if let Some(else_branch) = else_branch {
                    self.push_block("else", |this| {
                        for stmt in else_branch {
                            this.emit_statement(stmt);
                        }
                    });
                }
            }
            ASTNode::WhileStatement {
                condition, body, ..
            } => {
                let cond = self.emit_expression(condition);
                self.push_block(&format!("while ({})", cond), |this| {
                    for stmt in body {
                        this.emit_statement(stmt);
                    }
                });
            }
            ASTNode::ReturnStatement(expr_opt, _) => {
                if let Some(expr) = expr_opt {
                    let val = self.emit_expression(expr);
                    self.push_line(&format!("return {};", val));
                } else {
                    self.push_line("return;");
                }
            }
            ASTNode::Block { statements, .. } => {
                for stmt in statements {
                    self.emit_statement(stmt);
                }
            }
            ASTNode::CallExpr { .. } => {
                let expr_str = self.emit_expression(node);
                self.push_line(&format!("{};", expr_str));
            }
            _ => {
                let expr_str = self.emit_expression(node);
                if !expr_str.is_empty() {
                    self.push_line(&format!("{};", expr_str));
                }
            }
        }
    }

    // ------------------------------------------------------------------------
    // Expression emission
    // ------------------------------------------------------------------------
    fn emit_expression(&mut self, node: &ASTNode) -> String {
        match node {
            ASTNode::IntegerLiteral(v, _) => format!("{}", v),
            ASTNode::FloatLiteral(v, _) => format!("{:.10}", v),
            ASTNode::CharLiteral(c, _) => format!("{}", *c as i32),
            ASTNode::StringLiteral(s, _) => format!("\"{}\"", s),
            ASTNode::Identifier(name, _) => {
                // Check if this identifier is a scalar parameter being replaced by args->field
                if let Some(access) = self.scalar_access_map.get(name) {
                    access.clone()
                } else if let Some(access) = self.match_binding_map.get(name) {
                    access.clone()
                } else {
                    name.clone()
                }
            }
            ASTNode::BinaryExpr {
                left, op, right, ..
            } => {
                let l = self.emit_expression(left);
                let r = self.emit_expression(right);
                let op_str = match op {
                    crate::frontend::token::TokenKind::Plus => "+",
                    crate::frontend::token::TokenKind::Minus => "-",
                    crate::frontend::token::TokenKind::Star => "*",
                    crate::frontend::token::TokenKind::Div => "/",
                    crate::frontend::token::TokenKind::Mod => "%",
                    crate::frontend::token::TokenKind::Equal => "==",
                    crate::frontend::token::TokenKind::NotEqual => "!=",
                    crate::frontend::token::TokenKind::LessThan => "<",
                    crate::frontend::token::TokenKind::GreaterThan => ">",
                    crate::frontend::token::TokenKind::LessThanOrEqual => "<=",
                    crate::frontend::token::TokenKind::GreaterThanOrEqual => ">=",
                    crate::frontend::token::TokenKind::And => "&&",
                    crate::frontend::token::TokenKind::Or => "||",
                    crate::frontend::token::TokenKind::Ampersand => "&",
                    crate::frontend::token::TokenKind::Pipe => "|",
                    crate::frontend::token::TokenKind::Caret => "^",
                    crate::frontend::token::TokenKind::Shl => "<<",
                    crate::frontend::token::TokenKind::Shr => ">>",
                    _ => {
                        emit_diagnostic(
                            &Diagnostic::error(&format!(
                                "Unsupported binary operator in MSL: {:?}",
                                op
                            ))
                            .with_code("VX9001"),
                        );
                        "/*error*/"
                    }
                };
                format!("({} {} {})", l, op_str, r)
            }
            ASTNode::UnaryExpr { op, expr, .. } => {
                let inner = self.emit_expression(expr);
                match op {
                    crate::frontend::token::TokenKind::Not => format!("!{}", inner),
                    crate::frontend::token::TokenKind::Minus => format!("-{}", inner),
                    _ => format!("/*unary*/{}", inner),
                }
            }
            ASTNode::CastExpr {
                expr, target_type, ..
            } => {
                let inner = self.emit_expression(expr);
                let msl_ty = self.map_type(target_type);
                format!("({}){}", msl_ty, inner)
            }
            ASTNode::FieldAccess { expr, field, .. } => {
                let base = self.emit_expression(expr);
                format!("{}.{}", base, field)
            }
            ASTNode::ArrayIndex { array, index, .. } => {
                let arr = self.emit_expression(array);
                let idx = self.emit_expression(index);
                format!("{}[{}]", arr, idx)
            }
            ASTNode::CallExpr {
                callee,
                args,
                span: _,
            } => {
                let mut arg_exprs = Vec::new();
                for arg in args {
                    arg_exprs.push(self.emit_expression(arg));
                }
                let callee_name = match callee.as_str() {
                    "len" => "vox_len",
                    "assert" => "assert",
                    _ => callee,
                };
                format!("{}({})", callee_name, arg_exprs.join(", "))
            }
            ASTNode::StructLiteral { name, fields, .. } => {
                let mut field_exprs = Vec::new();
                for (fname, expr) in fields {
                    let val = self.emit_expression(expr);
                    field_exprs.push(format!(".{} = {}", fname, val));
                }
                format!("{}{{ {} }}", name, field_exprs.join(", "))
            }
            ASTNode::BorrowExpr { mutable, expr, .. } => {
                let inner = self.emit_expression(expr);
                if *mutable {
                    format!("&{}", inner)
                } else {
                    format!("&{}", inner)
                }
            }
            ASTNode::DerefExpr(expr, _) => {
                let inner = self.emit_expression(expr);
                format!("*{}", inner)
            }
            ASTNode::MatchExpr {
                value,
                arms,
                span: _,
            } => self.emit_match_expr(value, arms),
            _ => "/* unsupported expression */".to_string(),
        }
    }

    // ------------------------------------------------------------------------
    // Match expression emission (Phase 4)
    // ------------------------------------------------------------------------
    fn emit_match_expr(&mut self, value: &ASTNode, arms: &[MatchArm]) -> String {
        // 1. Emit the scrutinee expression
        let scr_val = self.emit_expression(value);

        // 2. Determine if any arm uses by_ref
        let any_by_ref = arms.iter().any(|arm| match &arm.pattern {
            MatchPattern::UnitVariant { by_ref, .. } => *by_ref,
            MatchPattern::Binding { by_ref, .. } => *by_ref,
            _ => false,
        });

        // 3. Get the scrutinee type and enum structure
        let scr_vox_ty = self.engine.infer_vox_type(value);
        let _enum_ty = self.map_type(&scr_vox_ty);
        let is_enum = self.is_enum_type(&scr_vox_ty);

        if !is_enum {
            emit_diagnostic(
                &Diagnostic::error(&format!(
                    "Match expression on non-enum type '{}'",
                    scr_vox_ty
                ))
                .with_code("VX9004"),
            );
            return "/* match on non-enum */".to_string();
        }

        // 4. Determine result type
        let result_type = if let Some(first_arm) = arms.first() {
            if let Some(expr) = first_arm.body.first() {
                self.engine.infer_vox_type(expr)
            } else {
                "i32".to_string()
            }
        } else {
            "i32".to_string()
        };
        let msl_result_type = self.map_type(&result_type);

        // 5. Build the match expression using a temporary variable
        let result_tmp = format!("__match_result_{}", self.engine.block_counter);
        self.engine.block_counter += 1;

        // Start building the match block
        let mut match_code = String::new();
        let indent = "    ".repeat(self.indent + 1);

        // Declare the result variable
        match_code.push_str(&format!(
            "{} {}: {} = {};\n",
            indent,
            result_tmp,
            msl_result_type,
            self.default_value(&msl_result_type)
        ));

        // Determine which arms are wildcard
        let has_wildcard = arms
            .iter()
            .any(|arm| matches!(arm.pattern, MatchPattern::Wildcard(_)));
        let mut seen_discriminants = Vec::new();

        for (idx, arm) in arms.iter().enumerate() {
            if matches!(arm.pattern, MatchPattern::Wildcard(_)) {
                continue;
            }

            let disc_value = match &arm.pattern {
                MatchPattern::UnitVariant { variant, .. } => {
                    // Find the discriminant for this variant
                    let enum_name = match value {
                        ASTNode::Identifier(name, _) => name.as_str(),
                        ASTNode::FieldAccess { expr: _, .. } => {
                            // Try to infer from the expression type
                            &scr_vox_ty
                        }
                        _ => &scr_vox_ty,
                    };
                    if let Some(d) = self.get_enum_discriminant(enum_name, variant) {
                        d
                    } else {
                        emit_diagnostic(
                            &Diagnostic::error(&format!(
                                "Unknown variant '{}' for enum '{}'",
                                variant, scr_vox_ty
                            ))
                            .with_code("VX9005"),
                        );
                        return "/* error */".to_string();
                    }
                }
                MatchPattern::Binding { variant, .. } => {
                    let enum_name = match value {
                        ASTNode::Identifier(name, _) => name.as_str(),
                        _ => &scr_vox_ty,
                    };
                    if let Some(d) = self.get_enum_discriminant(enum_name, variant) {
                        d
                    } else {
                        emit_diagnostic(
                            &Diagnostic::error(&format!(
                                "Unknown variant '{}' for enum '{}'",
                                variant, scr_vox_ty
                            ))
                            .with_code("VX9006"),
                        );
                        return "/* error */".to_string();
                    }
                }
                _ => {
                    emit_diagnostic(
                        &Diagnostic::error("Unsupported match pattern in MSL").with_code("VX9007"),
                    );
                    return "/* unsupported pattern */".to_string();
                }
            };

            // Avoid duplicate discriminants
            if seen_discriminants.contains(&disc_value) {
                continue;
            }
            seen_discriminants.push(disc_value);

            // Generate the condition
            let cond = if any_by_ref {
                format!("(*{}.discriminant) == {}", scr_val, disc_value)
            } else {
                format!("{}.discriminant == {}", scr_val, disc_value)
            };

            // For binding patterns, we need to extract the payload
            let is_binding = matches!(arm.pattern, MatchPattern::Binding { .. });

            // Generate the arm body
            let mut arm_code = String::new();
            if is_binding {
                // Save the current binding map
                let old_binding_map = self.match_binding_map.clone();

                // Extract bindings
                if let MatchPattern::Binding {
                    variant,
                    bindings,
                    by_ref: _,
                    enum_name: _,
                    span: _,
                } = &arm.pattern
                {
                    let payload_index = if CodegenEngine::strip_generic_args(&scr_vox_ty)
                        == "Result"
                        && variant == "Err"
                    {
                        2
                    } else {
                        1
                    };

                    for binding in bindings {
                        if binding == "_" {
                            continue;
                        }
                        // Determine the payload type
                        let payload_vox = if let Some((base_name, args)) =
                            crate::codegen::type_map::parse_generic_type(&scr_vox_ty)
                        {
                            if base_name == "Option" && args.len() == 1 {
                                args[0].clone()
                            } else if base_name == "Result" && args.len() == 2 {
                                if variant == "Ok" {
                                    args[0].clone()
                                } else {
                                    args[1].clone()
                                }
                            } else {
                                "i32".to_string()
                            }
                        } else {
                            "i32".to_string()
                        };
                        let _payload_msl = self.map_type(&payload_vox);

                        // Generate the payload access expression
                        let payload_expr = if any_by_ref {
                            format!("(*{}.field{})", scr_val, payload_index)
                        } else {
                            format!("{}.field{}", scr_val, payload_index)
                        };

                        // Store the access expression in the binding map
                        self.match_binding_map.insert(binding.clone(), payload_expr);
                    }
                }

                // Emit the arm body
                let mut arm_result = None;
                for stmt in &arm.body {
                    if let ASTNode::ReturnStatement(..) = stmt {
                        // Return statements are handled by the caller
                        self.emit_statement(stmt);
                        arm_result = None;
                        break;
                    } else {
                        arm_result = Some(self.emit_expression(stmt));
                    }
                }

                // Restore the old binding map
                self.match_binding_map = old_binding_map;

                if let Some(val) = arm_result {
                    arm_code.push_str(&format!("{} = {};\n", result_tmp, val));
                }
            } else {
                // Unit variant - no bindings
                let mut arm_result = None;
                for stmt in &arm.body {
                    if let ASTNode::ReturnStatement(..) = stmt {
                        self.emit_statement(stmt);
                        arm_result = None;
                        break;
                    } else {
                        arm_result = Some(self.emit_expression(stmt));
                    }
                }
                if let Some(val) = arm_result {
                    arm_code.push_str(&format!("{} = {};\n", result_tmp, val));
                }
            }

            // Add the arm with condition
            let cond_str = if idx == 0 {
                format!("if ({})", cond)
            } else {
                format!("else if ({})", cond)
            };
            match_code.push_str(&format!("{} {} {{\n", indent, cond_str));
            match_code.push_str(&arm_code);
            // Add break to exit the match
            match_code.push_str(&format!("{} break;\n", indent));
            match_code.push_str(&format!("{}}}\n", indent));
        }

        // 6. Handle wildcard or default panic
        if has_wildcard {
            let wildcard_arm = arms
                .iter()
                .find(|arm| matches!(arm.pattern, MatchPattern::Wildcard(_)))
                .unwrap();
            let mut arm_result = None;
            for stmt in &wildcard_arm.body {
                if let ASTNode::ReturnStatement(..) = stmt {
                    self.emit_statement(stmt);
                    arm_result = None;
                    break;
                } else {
                    arm_result = Some(self.emit_expression(stmt));
                }
            }
            if let Some(val) = arm_result {
                match_code.push_str(&format!("{} else {{\n", indent));
                match_code.push_str(&format!("{} = {};\n", result_tmp, val));
                match_code.push_str(&format!("{}}}\n", indent));
            }
        } else {
            // No wildcard - panic
            match_code.push_str(&format!("{} else {{\n", indent));
            match_code.push_str(&format!("{} /* match failed: panic */\n", indent));
            match_code.push_str(&format!("{}}}\n", indent));
        }

        // Wrap the match in a block and return the result
        let _match_block = format!("{{\n{}{}}}\n", match_code, "    ".repeat(self.indent + 1));

        // Return the result variable
        format!("{}", result_tmp)
    }

    /// Return a default value for a given MSL type.
    fn default_value(&self, msl_ty: &str) -> String {
        match msl_ty {
            "int" | "uint" | "short" | "ushort" | "char" | "uchar" | "long" | "ulong" | "float"
            | "double" | "bool" => "0".to_string(),
            "void" => "".to_string(),
            s if s.ends_with('*') => "nullptr".to_string(),
            s if s.starts_with("struct") => format!("{}()", s),
            _ => "0".to_string(),
        }
    }
}
